apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: netto
spec:
  selector:
    matchLabels:
      app: netto
  template:
    metadata:
      labels:
        app: netto
    spec:
      containers:
      - name: netto
        image: {{ .Values.netto.image }}
        imagePullPolicy: "{{ .Values.netto.pullPolicy }}"
        securityContext:
          privileged: true
        args:
          - --address
          - "{{ .Values.netto.address }}"
        ports:
        - containerPort: 80
        env:
        - name: NETTO_HOST
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
