apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pyroscope
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyroscope
  template:
    metadata:
      labels:
        app: pyroscope
    spec:
      containers:
      - name: pyroscope
        image: {{ .Values.pyroscope.image }}
        ports:
        - containerPort: 4040

